config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
  get 'notes', to: 'notes#index'
  get 'about', to: 'pages#about_us'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @h1 = 'Заметки'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @h1 = 'Главная'
  end

  def about_us
    @h1 = 'О нас'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul>
    <li><%= link_to 'Index', root_path, class: 'index'%></li>
    <li><%= link_to 'Notes', notes_path, class: 'notes'%></li>
    <li><%= link_to 'About', about_path, class: 'about'%></li>
  </ul>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<h1><%= @h1 %></h1>

app/views/pages/about_us.html.erb
<h1><%= @h1 %></h1>

app/views/pages/index.html.erb
<h1><%= @h1 %></h1>